# Generated by Django 4.0.1 on 2022-01-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('insdate', models.DateField(auto_now_add=True, verbose_name='insert date')),
                ('duedate', models.DateField(verbose_name='due date')),
                ('priority', models.CharField(choices=[('LO', 'LOW'), ('ME', 'MEDIUM'), ('HI', 'HIGH')], default='ME', max_length=2, verbose_name='prority')),
                ('done', models.BooleanField(default=False, verbose_name='completed')),
            ],
        ),
    ]
