# Generated by Django 4.0.1 on 2022-01-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoBeeDoBeeDoo', '0002_alter_task_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duedate',
            field=models.DateField(blank=True, null=True, verbose_name='due date'),
        ),
    ]
