# Generated by Django 4.0.1 on 2022-01-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoBeeDoBeeDoo', '0003_alter_task_duedate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('duedate',)},
        ),
    ]
