# Generated by Django 4.0.1 on 2022-02-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoBeeDoBeeDoo', '0004_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
