# Generated by Django 4.0.1 on 2022-02-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoBeeDoBeeDoo', '0005_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('insdate', models.DateField(auto_now_add=True, verbose_name='insert date')),
            ],
        ),
    ]
