# Generated by Django 4.0.1 on 2022-03-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoBeeDoBeeDoo', '0007_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LO', 'LOW'), ('ME', 'MEDIUM'), ('HI', 'HIGH')], default='ME', max_length=2, verbose_name='prority'),
        ),
    ]
