# Generated by Django 4.0.1 on 2022-03-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoBeeDoBeeDoo', '0008_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'LOW'), ('M', 'MEDIUM'), ('H', 'HIGH')], default='M', max_length=1, verbose_name='prority'),
        ),
    ]
